"""empty message

Revision ID: 86ea7f9ce4b7
Revises: f06e9860d909
Create Date: 2019-06-21 01:07:04.583669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ea7f9ce4b7'
down_revision = 'f06e9860d909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user', sa.Column('pwd_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_user', 'pwd_hash')
    # ### end Alembic commands ###
