"""empty message

Revision ID: f06e9860d909
Revises: 3fe5f950f723
Create Date: 2019-06-19 19:24:06.539270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f06e9860d909'
down_revision = '3fe5f950f723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user', sa.Column('avatar_url', sa.String(length=100), nullable=True))
    op.add_column('ihome_user', sa.Column('real_id_card', sa.String(length=18), nullable=True))
    op.add_column('ihome_user', sa.Column('real_name', sa.String(length=30), nullable=True))
    op.drop_index('id_card', table_name='ihome_user')
    op.create_unique_constraint(None, 'ihome_user', ['real_id_card'])
    op.drop_column('ihome_user', 'id_card')
    op.drop_column('ihome_user', 'pwd_hash')
    op.drop_column('ihome_user', 'id_name')
    op.drop_column('ihome_user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user', sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('ihome_user', sa.Column('id_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('ihome_user', sa.Column('pwd_hash', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ihome_user', sa.Column('id_card', mysql.VARCHAR(length=18), nullable=True))
    op.drop_constraint(None, 'ihome_user', type_='unique')
    op.create_index('id_card', 'ihome_user', ['id_card'], unique=True)
    op.drop_column('ihome_user', 'real_name')
    op.drop_column('ihome_user', 'real_id_card')
    op.drop_column('ihome_user', 'avatar_url')
    # ### end Alembic commands ###
